Web clone
lily-coder/newsweek-web-clone pull request #5
Opened 2021-04-17 15:57 UTC by lily-coder

This is milestone three of the clone of the Newsweek web page 
I have worked on the changes as requested by the reviewer in the previous pull request

2021-04-17 17:02 UTC, sinansevgi requested changes
# Status: Changes Required ♻️ 

Good job! 
You fixed the issue with image alignments. But as previous TSE pointed out you still should fix below issues:

- [ ] Your images in sections look stretched and higher than they should be.
![Screenshot_2021-04-17 NewsWeek](https://user-images.githubusercontent.com/1642014/115120510-8a6a0400-9fb6-11eb-8c36-cf34db56f31f.png)

- [ ]  Newsletter subscription section doesn't look similar to original on mobile resolution

Yours
![Screenshot_2021-04-17 NewsWeek(1)](https://user-images.githubusercontent.com/1642014/115120600-006e6b00-9fb7-11eb-9103-ab0b24f51bce.png)

Original
![Screenshot_2021-04-17 Newsweek](https://user-images.githubusercontent.com/1642014/115120608-082e0f80-9fb7-11eb-9980-8c69415c286f.png)

- [ ] First article of in the magazine section still doesn't looks as original

![Screenshot_2021-04-17 NewsWeek(2)](https://user-images.githubusercontent.com/1642014/115120752-c2be1200-9fb7-11eb-8f50-30aaa6a3efcf.png)

----------------------------------
Optional 
- [ ] Please remove unnecessary white space from project it will look unprofessional.
---------------------------------

"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, [you can request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "

-----
You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

2021-04-17 17:02 UTC, sinansevgi commented on index.html
> +                  <img class="card-img" src="/img/newsweekpage.jpg" alt="">
```suggestion
                  <img class="card-img" src="./img/newsweekpage.jpg" alt="">
```
Without dot your image is not visible.

2021-04-18 01:14 UTC, lily-coder commented on index.html
> +                  <img class="card-img" src="/img/newsweekpage.jpg" alt="">
okay, corrected that

2021-04-18 04:26 UTC, elisha2kyakpo1 approved these changes
🎉💪✔**Congratulations @lily-coder, I'm happy to see all the changes requested being implemented**
I'm wishing you the best as you face bigger programs.

**[OPTIONAL] You can fix the images, they are not uniform, you can use background-image in CSS so that you have more control**
Cheers.💪👍

2021-04-18 08:13 UTC, merged